# Generated by Django 6.0.5 on 2026-05-18 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonCreditBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50, unique=True)),
                ('vintage_year', models.IntegerField(help_text='Year credits were generated')),
                ('total_tons', models.FloatField()),
                ('sold_to', models.CharField(blank=True, max_length=100)),
                ('price_per_ton_usd', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('total_revenue_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payout_pool_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('farmer_bonus_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('operations_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('verification_method', models.CharField(default='Verra VM0042', max_length=100)),
                ('verification_body', models.CharField(blank=True, max_length=100)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('verification_report', models.FileField(blank=True, upload_to='verification_reports/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified'), ('listed', 'Listed for Sale'), ('sold', 'Sold'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-vintage_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('landmark', models.CharField(blank=True, help_text='Nearest landmark for farmers without GPS', max_length=200)),
                ('altitude_meters', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('crop_type', models.CharField(choices=[('maize', 'Maize'), ('beans', 'Beans'), ('mixed', 'Mixed Cereals'), ('vegetables', 'Vegetables'), ('coffee', 'Coffee'), ('tea', 'Tea'), ('other', 'Other')], default='maize', max_length=20)),
                ('area_acres', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('soil_type', models.CharField(blank=True, choices=[('clay', 'Clay'), ('sandy', 'Sandy'), ('loam', 'Loam'), ('silt', 'Silt'), ('other', 'Other')], max_length=20)),
                ('regenerative_practices', models.JSONField(default=list, help_text='List of regenerative practices used')),
                ('years_practicing', models.IntegerField(default=0, help_text='Years using regenerative practices')),
                ('carbon_sequestered_tons', models.FloatField(default=0.0, help_text='Estimated tons CO2 per year')),
                ('carbon_credits_issued', models.FloatField(default=0.0)),
                ('carbon_credits_sold', models.FloatField(default=0.0)),
                ('last_carbon_assessment', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_monitored', models.BooleanField(default=True, help_text='Whether satellite monitoring is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DroughtEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('consecutive_dry_days', models.IntegerField()),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Mild (5-10 days dry)'), ('moderate', 'Moderate (10-15 days dry)'), ('severe', 'Severe (15-20 days dry)'), ('extreme', 'Extreme (20+ days dry)')], max_length=20)),
                ('rainfall_actual_mm', models.FloatField(help_text='Actual rainfall during drought period')),
                ('rainfall_avg_mm', models.FloatField(help_text='30-year average rainfall for same period')),
                ('rainfall_percentage', models.FloatField(default=0, help_text='Actual/AVG * 100')),
                ('crop_stage_at_event', models.CharField(blank=True, choices=[('planting', 'Planting'), ('germination', 'Germination'), ('vegetative', 'Vegetative Growth'), ('flowering', 'Flowering'), ('filling', 'Grain Filling'), ('maturation', 'Maturation'), ('harvest', 'Harvest')], max_length=20)),
                ('is_triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_amount_kes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_source', models.CharField(default='NASA_POWER', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drought_events', to='core.farm')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='M', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('has_disability', models.BooleanField(default=False)),
                ('disability_type', models.CharField(choices=[('none', 'None'), ('blind', 'Blind/Low Vision'), ('deaf', 'Deaf/Hard of Hearing'), ('mobility', 'Mobility Impairment'), ('cognitive', 'Cognitive Disability'), ('other', 'Other')], default='none', max_length=20)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili')], default='en', max_length=10)),
                ('registered_via', models.CharField(choices=[('ussd', 'USSD'), ('voice', 'Voice Call'), ('sms', 'SMS'), ('web', 'Website'), ('agent', 'Field Agent')], default='ussd', max_length=20)),
                ('mpesa_phone', models.CharField(blank=True, help_text='Phone number for M-Pesa payouts', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='core.farmer'),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_type', models.CharField(choices=[('drought', 'Drought Insurance'), ('bonus_women', 'Women Empowerment Bonus'), ('bonus_pwd', 'PWD Bonus'), ('carbon_bonus', 'Carbon Credit Bonus'), ('top_up', 'Emergency Top-up')], default='drought', max_length=20)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_transaction_id', models.CharField(blank=True, max_length=50)),
                ('mpesa_result_code', models.CharField(blank=True, max_length=10)),
                ('mpesa_result_desc', models.CharField(blank=True, max_length=200)),
                ('recipient_phone', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('status_message', models.CharField(blank=True, max_length=200)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('drought_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='core.droughtevent')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='core.farmer')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RainfallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rainfall_mm', models.FloatField()),
                ('source', models.CharField(choices=[('NASA_POWER', 'NASA POWER'), ('CHIRPS', 'CHIRPS'), ('GPM', 'Global Precipitation Measurement'), ('ground', 'Ground Station')], default='NASA_POWER', max_length=20)),
                ('thirty_year_avg_mm', models.FloatField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_records', to='core.farm')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='droughtevent',
            index=models.Index(fields=['farm', 'is_triggered'], name='core_drough_farm_id_e08d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='droughtevent',
            index=models.Index(fields=['start_date'], name='core_drough_start_d_09f819_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['phone_number'], name='core_farmer_phone_n_c72073_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['is_active'], name='core_farmer_is_acti_8e4901_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['county'], name='core_farmer_county_770e77_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['farmer', 'is_active'], name='core_farm_farmer__3e7711_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['latitude', 'longitude'], name='core_farm_latitud_ca7914_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['farmer', 'status'], name='core_payout_farmer__c3044c_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', 'requested_at'], name='core_payout_status_b2d89d_idx'),
        ),
        migrations.AddIndex(
            model_name='rainfallrecord',
            index=models.Index(fields=['farm', 'date'], name='core_rainfa_farm_id_ffacee_idx'),
        ),
        migrations.AddIndex(
            model_name='rainfallrecord',
            index=models.Index(fields=['date'], name='core_rainfa_date_814016_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rainfallrecord',
            unique_together={('farm', 'date')},
        ),
    ]
